name: deploy to common

on:
  pull_request:
    types: [closed]

permissions:
  actions: read
  contents: read

jobs:
  find-run:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'robot/')
    runs-on: ubuntu-latest
    outputs:
      runid: ${{ steps.find.outputs.runid }}
    steps:
      - name: Find successful build run for this PR commit
        id: find
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr = context.payload.pull_request;
            const headRef = pr.head.ref;
            const headSha = pr.head.sha;

            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForWorkflow, {
              owner,
              repo,
              workflow_id: 'build.yml',
              event: 'pull_request',
              branch: headRef,
              status: 'completed',
              per_page: 100
            });

            let match = runs.find(r => r.head_sha === headSha && r.conclusion === 'success');
            if (!match) {
              match = runs.find(r => r.conclusion === 'success' && r.pull_requests?.some(p => p.number === pr.number));
            }
            if (!match) {
              core.setFailed(`No successful 'build' workflow run found for branch ${headRef} (PR #${pr.number}).`);
              return;
            }
            core.info(`Using build run id: ${match.id} (head_sha=${match.head_sha})`);
            core.setOutput('runid', String(match.id))

  deploy:
    needs: find-run
    if: needs.find-run.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      runid: ${{ needs.find-run.outputs.runid }}